apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aviary-admin.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "aviary-admin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "aviary-admin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aviary-admin.labels" . | nindent 8 }}
    spec:
      {{- if .Values.hostGatewayIP }}
      hostAliases:
        - ip: {{ .Values.hostGatewayIP | quote }}
          hostnames: ["host.k8s.internal"]
      {{- end }}
      containers:
        - name: admin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.config.databaseURL | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
