healthCheckTimeout: 300
logLevel: info

models:
  "gemma-4-26b":
    cmd: |
      llama-server
      --hf-repo unsloth/gemma-4-26B-A4B-it-GGUF
      --hf-file gemma-4-26B-A4B-it-UD-Q4_K_M.gguf
      -c 65536
      --port ${PORT}
    ttl: 600
    aliases:
      - "gemma4"
